// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/view_projection3d.fbs".

#include "view_projection3d.hpp"

#include "../../collection_adapter_builtins.hpp"

namespace rerun::blueprint::archetypes {
    ViewProjection3D ViewProjection3D::clear_fields() {
        auto archetype = ViewProjection3D();
        archetype.kind =
            ComponentBatch::empty<rerun::blueprint::components::ProjectionKind3D>(Descriptor_kind)
                .value_or_throw();
        archetype.orthographic_scale =
            ComponentBatch::empty<rerun::blueprint::components::OrthographicScale>(
                Descriptor_orthographic_scale
            )
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> ViewProjection3D::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(3);
        if (kind.has_value()) {
            columns.push_back(kind.value().partitioned(lengths_).value_or_throw());
        }
        if (orthographic_scale.has_value()) {
            columns.push_back(orthographic_scale.value().partitioned(lengths_).value_or_throw());
        }
        columns.push_back(ComponentColumn::from_indicators<ViewProjection3D>(
                              static_cast<uint32_t>(lengths_.size())
        )
                              .value_or_throw());
        return columns;
    }

    Collection<ComponentColumn> ViewProjection3D::columns() {
        if (kind.has_value()) {
            return columns(std::vector<uint32_t>(kind.value().length(), 1));
        }
        if (orthographic_scale.has_value()) {
            return columns(std::vector<uint32_t>(orthographic_scale.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::blueprint::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>>
        AsComponents<blueprint::archetypes::ViewProjection3D>::as_batches(
            const blueprint::archetypes::ViewProjection3D& archetype
        ) {
        using namespace blueprint::archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(3);

        if (archetype.kind.has_value()) {
            cells.push_back(archetype.kind.value());
        }
        if (archetype.orthographic_scale.has_value()) {
            cells.push_back(archetype.orthographic_scale.value());
        }
        {
            auto result = ComponentBatch::from_indicator<ViewProjection3D>();
            RR_RETURN_NOT_OK(result.error);
            cells.emplace_back(std::move(result.value));
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
