// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/view_projection3d.fbs".

#pragma once

#include "../../blueprint/components/orthographic_scale.hpp"
#include "../../blueprint/components/projection_kind3d.hpp"
#include "../../collection.hpp"
#include "../../component_batch.hpp"
#include "../../component_column.hpp"
#include "../../indicator_component.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::blueprint::archetypes {
    /// **Archetype**: Projection settings for a `Spatial3DView`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ViewProjection3D {
        /// Projection mode used by the 3D view.
        std::optional<ComponentBatch> kind;

        /// Vertical world size used when the projection is orthographic.
        ///
        /// Values less than or equal to zero mean automatic scene fitting.
        std::optional<ComponentBatch> orthographic_scale;

      public:
        static constexpr const char IndicatorComponentName[] =
            "rerun.blueprint.components.ViewProjection3DIndicator";

        /// Indicator component, used to identify the archetype when converting to a list of components.
        using IndicatorComponent = rerun::components::IndicatorComponent<IndicatorComponentName>;
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.blueprint.archetypes.ViewProjection3D";

        /// `ComponentDescriptor` for the `kind` field.
        static constexpr auto Descriptor_kind = ComponentDescriptor(
            ArchetypeName, "kind",
            Loggable<rerun::blueprint::components::ProjectionKind3D>::Descriptor.component_name
        );
        /// `ComponentDescriptor` for the `orthographic_scale` field.
        static constexpr auto Descriptor_orthographic_scale = ComponentDescriptor(
            ArchetypeName, "orthographic_scale",
            Loggable<rerun::blueprint::components::OrthographicScale>::Descriptor.component_name
        );

      public:
        ViewProjection3D() = default;
        ViewProjection3D(ViewProjection3D&& other) = default;
        ViewProjection3D(const ViewProjection3D& other) = default;
        ViewProjection3D& operator=(const ViewProjection3D& other) = default;
        ViewProjection3D& operator=(ViewProjection3D&& other) = default;

        /// Update only some specific fields of a `ViewProjection3D`.
        static ViewProjection3D update_fields() {
            return ViewProjection3D();
        }

        /// Clear all the fields of a `ViewProjection3D`.
        static ViewProjection3D clear_fields();

        /// Projection mode used by the 3D view.
        ViewProjection3D with_kind(const rerun::blueprint::components::ProjectionKind3D& _kind) && {
            kind = ComponentBatch::from_loggable(_kind, Descriptor_kind).value_or_throw();
            return std::move(*this);
        }

        /// Vertical world size used when the projection is orthographic.
        ///
        /// Values less than or equal to zero mean automatic scene fitting.
        ViewProjection3D with_orthographic_scale(
            const rerun::blueprint::components::OrthographicScale& _orthographic_scale
        ) && {
            orthographic_scale =
                ComponentBatch::from_loggable(_orthographic_scale, Descriptor_orthographic_scale)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::blueprint::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<blueprint::archetypes::ViewProjection3D> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const blueprint::archetypes::ViewProjection3D& archetype
        );
    };
} // namespace rerun
