# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/view_projection3d.fbs".

# You can extend this class by creating a "ViewProjection3DExt" class in "view_projection3d_ext.py".

from __future__ import annotations

from typing import Any

from attrs import define, field

from ... import datatypes
from ..._baseclasses import (
    Archetype,
)
from ...blueprint import components as blueprint_components
from ...error_utils import catch_and_log_exceptions

__all__ = ["ViewProjection3D"]


@define(str=False, repr=False, init=False)
class ViewProjection3D(Archetype):
    """
    **Archetype**: Projection settings for a `Spatial3DView`.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(
        self: Any,
        *,
        kind: blueprint_components.ProjectionKind3DLike | None = None,
        orthographic_scale: datatypes.Float32Like | None = None,
    ) -> None:
        """
        Create a new instance of the ViewProjection3D archetype.

        Parameters
        ----------
        kind:
            Projection mode used by the 3D view.
        orthographic_scale:
            Vertical world size used when the projection is orthographic.

            Values less than or equal to zero mean automatic scene fitting.

        """

        # You can define your own __init__ function as a member of ViewProjection3DExt in view_projection3d_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(kind=kind, orthographic_scale=orthographic_scale)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            kind=None,
            orthographic_scale=None,
        )

    @classmethod
    def _clear(cls) -> ViewProjection3D:
        """Produce an empty ViewProjection3D, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        kind: blueprint_components.ProjectionKind3DLike | None = None,
        orthographic_scale: datatypes.Float32Like | None = None,
    ) -> ViewProjection3D:
        """
        Update only some specific fields of a `ViewProjection3D`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        kind:
            Projection mode used by the 3D view.
        orthographic_scale:
            Vertical world size used when the projection is orthographic.

            Values less than or equal to zero mean automatic scene fitting.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "kind": kind,
                "orthographic_scale": orthographic_scale,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> ViewProjection3D:
        """Clear all the fields of a `ViewProjection3D`."""
        return cls.from_fields(clear_unset=True)

    kind: blueprint_components.ProjectionKind3DBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.ProjectionKind3DBatch._converter,  # type: ignore[misc]
    )
    # Projection mode used by the 3D view.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    orthographic_scale: blueprint_components.OrthographicScaleBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.OrthographicScaleBatch._converter,  # type: ignore[misc]
    )
    # Vertical world size used when the projection is orthographic.
    #
    # Values less than or equal to zero mean automatic scene fitting.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
