// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/view_projection3d.fbs".

#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]

use ::re_types_core::try_serialize_field;
use ::re_types_core::SerializationResult;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentName};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Projection settings for a `Spatial3DView`.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default)]
pub struct ViewProjection3D {
    /// Projection mode used by the 3D view.
    pub kind: Option<SerializedComponentBatch>,

    /// Vertical world size used when the projection is orthographic.
    ///
    /// Values less than or equal to zero mean automatic scene fitting.
    pub orthographic_scale: Option<SerializedComponentBatch>,
}

impl ViewProjection3D {
    /// Returns the [`ComponentDescriptor`] for [`Self::kind`].
    #[inline]
    pub fn descriptor_kind() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.ViewProjection3D".into()),
            component_name: "rerun.blueprint.components.ProjectionKind3D".into(),
            archetype_field_name: Some("kind".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::orthographic_scale`].
    #[inline]
    pub fn descriptor_orthographic_scale() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.ViewProjection3D".into()),
            component_name: "rerun.blueprint.components.OrthographicScale".into(),
            archetype_field_name: Some("orthographic_scale".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for the associated indicator component.
    #[inline]
    pub fn descriptor_indicator() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.ViewProjection3D".into()),
            component_name: "rerun.blueprint.components.ViewProjection3DIndicator".into(),
            archetype_field_name: None,
        }
    }
}

static REQUIRED_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 0usize]> =
    once_cell::sync::Lazy::new(|| []);

static RECOMMENDED_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 1usize]> =
    once_cell::sync::Lazy::new(|| [ViewProjection3D::descriptor_indicator()]);

static OPTIONAL_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 2usize]> =
    once_cell::sync::Lazy::new(|| {
        [
            ViewProjection3D::descriptor_kind(),
            ViewProjection3D::descriptor_orthographic_scale(),
        ]
    });

static ALL_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 3usize]> =
    once_cell::sync::Lazy::new(|| {
        [
            ViewProjection3D::descriptor_indicator(),
            ViewProjection3D::descriptor_kind(),
            ViewProjection3D::descriptor_orthographic_scale(),
        ]
    });

impl ViewProjection3D {
    /// The total number of components in the archetype: 0 required, 1 recommended, 2 optional
    pub const NUM_COMPONENTS: usize = 3usize;
}

/// Indicator component for the [`ViewProjection3D`] [`::re_types_core::Archetype`]
pub type ViewProjection3DIndicator = ::re_types_core::GenericIndicatorComponent<ViewProjection3D>;

impl ::re_types_core::Archetype for ViewProjection3D {
    type Indicator = ViewProjection3DIndicator;

    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.blueprint.archetypes.ViewProjection3D".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "View projection 3D"
    }

    #[inline]
    fn indicator() -> SerializedComponentBatch {
        #[allow(clippy::unwrap_used)]
        ViewProjection3DIndicator::DEFAULT.serialized().unwrap()
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let kind = arrays_by_descr
            .get(&Self::descriptor_kind())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_kind()));
        let orthographic_scale = arrays_by_descr
            .get(&Self::descriptor_orthographic_scale())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_orthographic_scale())
            });
        Ok(Self {
            kind,
            orthographic_scale,
        })
    }
}

impl ::re_types_core::AsComponents for ViewProjection3D {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            Some(Self::indicator()),
            self.kind.clone(),
            self.orthographic_scale.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for ViewProjection3D {}

impl ViewProjection3D {
    /// Create a new `ViewProjection3D`.
    #[inline]
    pub fn new() -> Self {
        Self {
            kind: None,
            orthographic_scale: None,
        }
    }

    /// Update only some specific fields of a `ViewProjection3D`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `ViewProjection3D`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            kind: Some(SerializedComponentBatch::new(
                crate::blueprint::components::ProjectionKind3D::arrow_empty(),
                Self::descriptor_kind(),
            )),
            orthographic_scale: Some(SerializedComponentBatch::new(
                crate::blueprint::components::OrthographicScale::arrow_empty(),
                Self::descriptor_orthographic_scale(),
            )),
        }
    }

    /// Projection mode used by the 3D view.
    #[inline]
    pub fn with_kind(
        mut self,
        kind: impl Into<crate::blueprint::components::ProjectionKind3D>,
    ) -> Self {
        self.kind = try_serialize_field(Self::descriptor_kind(), [kind]);
        self
    }

    /// Vertical world size used when the projection is orthographic.
    ///
    /// Values less than or equal to zero mean automatic scene fitting.
    #[inline]
    pub fn with_orthographic_scale(
        mut self,
        orthographic_scale: impl Into<crate::blueprint::components::OrthographicScale>,
    ) -> Self {
        self.orthographic_scale =
            try_serialize_field(Self::descriptor_orthographic_scale(), [orthographic_scale]);
        self
    }
}

impl ::re_byte_size::SizeBytes for ViewProjection3D {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.kind.heap_size_bytes() + self.orthographic_scale.heap_size_bytes()
    }
}
