# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_types/definitions/rerun/blueprint/components/orthographic_scale.fbs".

# You can extend this class by creating a "OrthographicScaleExt" class in "orthographic_scale_ext.py".

from __future__ import annotations

from ... import datatypes
from ..._baseclasses import (
    ComponentBatchMixin,
    ComponentDescriptor,
    ComponentMixin,
)

__all__ = ["OrthographicScale", "OrthographicScaleBatch"]


class OrthographicScale(datatypes.Float32, ComponentMixin):
    """
    **Component**: Vertical world size used by an orthographic `Spatial3DView`.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of OrthographicScaleExt in orthographic_scale_ext.py

    # Note: there are no fields here because OrthographicScale delegates to datatypes.Float32


class OrthographicScaleBatch(datatypes.Float32Batch, ComponentBatchMixin):
    _COMPONENT_DESCRIPTOR: ComponentDescriptor = ComponentDescriptor("rerun.blueprint.components.OrthographicScale")


# This is patched in late to avoid circular dependencies.
OrthographicScale._BATCH_TYPE = OrthographicScaleBatch  # type: ignore[assignment]
