# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_types/definitions/rerun/blueprint/components/projection_kind3d.fbs".

# You can extend this class by creating a "ProjectionKind3DExt" class in "projection_kind3d_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal, Union

import pyarrow as pa

from ..._baseclasses import (
    BaseBatch,
    ComponentBatchMixin,
    ComponentDescriptor,
)

__all__ = ["ProjectionKind3D", "ProjectionKind3DArrayLike", "ProjectionKind3DBatch", "ProjectionKind3DLike"]


from enum import Enum


class ProjectionKind3D(Enum):
    """**Component**: Projection mode used by a `Spatial3DView`."""

    Perspective = 1
    """Perspective projection."""

    Orthographic = 2
    """Orthographic projection."""

    @classmethod
    def auto(cls, val: str | int | ProjectionKind3D) -> ProjectionKind3D:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, ProjectionKind3D):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


ProjectionKind3DLike = Union[
    ProjectionKind3D, Literal["Orthographic", "Perspective", "orthographic", "perspective"], int
]
ProjectionKind3DArrayLike = Union[ProjectionKind3DLike, Sequence[ProjectionKind3DLike]]


class ProjectionKind3DBatch(BaseBatch[ProjectionKind3DArrayLike], ComponentBatchMixin):
    _ARROW_DATATYPE = pa.uint8()
    _COMPONENT_DESCRIPTOR: ComponentDescriptor = ComponentDescriptor("rerun.blueprint.components.ProjectionKind3D")

    @staticmethod
    def _native_to_pa_array(data: ProjectionKind3DArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (ProjectionKind3D, int, str)):
            data = [data]

        pa_data = [ProjectionKind3D.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]

        return pa.array(pa_data, type=data_type)
