// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/components/orthographic_scale.fbs".

#pragma once

#include "../../component_descriptor.hpp"
#include "../../datatypes/float32.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::blueprint::components {
    /// **Component**: Vertical world size used by an orthographic `Spatial3DView`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct OrthographicScale {
        /// Vertical world size.
        ///
        /// Values less than or equal to zero mean automatic scene fitting.
        rerun::datatypes::Float32 scale;

      public:
        OrthographicScale() = default;

        OrthographicScale(rerun::datatypes::Float32 scale_) : scale(scale_) {}

        OrthographicScale& operator=(rerun::datatypes::Float32 scale_) {
            scale = scale_;
            return *this;
        }

        OrthographicScale(float value_) : scale(value_) {}

        OrthographicScale& operator=(float value_) {
            scale = value_;
            return *this;
        }

        /// Cast to the underlying Float32 datatype
        operator rerun::datatypes::Float32() const {
            return scale;
        }
    };
} // namespace rerun::blueprint::components

namespace rerun {
    static_assert(
        sizeof(rerun::datatypes::Float32) == sizeof(blueprint::components::OrthographicScale)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::OrthographicScale> {
        static constexpr ComponentDescriptor Descriptor =
            "rerun.blueprint.components.OrthographicScale";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Float32>::arrow_datatype();
        }

        /// Serializes an array of `rerun::blueprint:: components::OrthographicScale` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::OrthographicScale* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Float32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Float32>::to_arrow(
                    &instances->scale,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
