// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/components/projection_kind3d.fbs".

#pragma once

#include "../../component_descriptor.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt8Type;
    using UInt8Builder = NumericBuilder<UInt8Type>;
} // namespace arrow

namespace rerun::blueprint::components {
    /// **Component**: Projection mode used by a `Spatial3DView`.
    enum class ProjectionKind3D : uint8_t {

        /// Perspective projection.
        Perspective = 1,

        /// Orthographic projection.
        Orthographic = 2,
    };
} // namespace rerun::blueprint::components

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<blueprint::components::ProjectionKind3D> {
        static constexpr ComponentDescriptor Descriptor =
            "rerun.blueprint.components.ProjectionKind3D";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::blueprint:: components::ProjectionKind3D` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::ProjectionKind3D* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt8Builder* builder, const blueprint::components::ProjectionKind3D* elements,
            size_t num_elements
        );
    };
} // namespace rerun
